const weightliftingExercises = [
    "Back Squat",
    "Clean & Jerk",
    "Clean Deadlift",
    "Clean High Pull",
    "Clean Pull",
    "Deficit Deadlift",
    "Deadlift",
    "Drop Snatch",
    "Front Squat",
    "Hang Clean",
    "Hang Snatch",
    "Heaving Snatch Balance",
    "Jerk",
    "Muscle Clean",
    "Muscle Snatch",
    "Overhead Squat",
    "Power Clean",
    "Power Jerk",
    "Power Snatch",
    "Pressing Snatch Balance",
    "Push Jerk",
    "Push Press",
    "Rack Jerk",
    "Romanian Deadlift",
    "Snatch",
    "Snatch Balance",
    "Snatch Deadlift",
    "Snatch High Pull",
    "Snatch Pull",
    "Split Jerk",
    "Strict Press",
    "Sumo Deadlift",
    "Sumo Deadlift High Pull",
    "Thruster",
    "Weighted Dip",
    "Weighted Pull-Up",
    "Weighted Chin-Up",
    "Weighted Push-Up",
    "Weighted Sit-Up",
    "Weighted Pistol Squat",
    "Weighted Lunge",
    "Weighted Box Jump",
    "Weighted Muscle-Up",
    "Weighted Handstand Push-Up",
    "Weighted Step-Up",
    "Weighted Walking Lunge"
];

export default weightliftingExercises;